using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace MasterDetail
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            //WindowState = FormWindowState.Maximized;

            // This line of code is generated by Data Source Configuration Wizard
            this.pLinqInstantFeedbackSource1.GetEnumerable += pLinqInstantFeedbackSource1_GetEnumerable;
            // This line of code is generated by Data Source Configuration Wizard
            this.pLinqInstantFeedbackSource1.DismissEnumerable += pLinqInstantFeedbackSource1_DismissEnumerable;
        }

        // This event is generated by Data Source Configuration Wizard
        void pLinqInstantFeedbackSource1_GetEnumerable(object sender, DevExpress.Data.PLinq.GetEnumerableEventArgs e)
        {
            // Instantiate a new DataContext
            MasterDetail.Folder.EmailContext dataContext = new MasterDetail.Folder.EmailContext();
            // Assign a queryable source to the PLinqInstantFeedbackSource
            e.Source = dataContext.adr__Ewid;
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissEnumerable event handler
            e.Tag = dataContext;
        }

        // This event is generated by Data Source Configuration Wizard
        void pLinqInstantFeedbackSource1_DismissEnumerable(object sender, DevExpress.Data.PLinq.GetEnumerableEventArgs e)
        {
            // Dispose of the DataContext
            ((MasterDetail.Folder.EmailContext)e.Tag).Dispose();
        }

        private void Towar_Click(object sender, EventArgs e)
        {
            Console.WriteLine("Towar");
        }

        private void Kontrahent_Click(object sender, EventArgs e)
        {
            Console.WriteLine("Kontrahent");
        }

        private void Dokument_Click(object sender, EventArgs e)
        {
            Console.WriteLine("Dokument");
        }
    }
}
