// <auto-generated />
using System;
using MasterDetail;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterDetail.Migrations
{
    [DbContext(typeof(Folder.EmailContext))]
    partial class EmailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasterDetail.AdrEwid", b =>
            {
                b.Property<int>("adr_Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("adr_Adres")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime?>("adr_DataZmiany")
                    .HasColumnType("datetime2");

                b.Property<string>("adr_Faks")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Gmina")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("adr_IdGminy")
                    .HasColumnType("int");

                b.Property<int>("adr_IdObiektu")
                    .HasColumnType("int");

                b.Property<int?>("adr_IdPanstwo")
                    .HasColumnType("int");

                b.Property<int?>("adr_IdWersja")
                    .HasColumnType("int");

                b.Property<int?>("adr_IdWojewodztwo")
                    .HasColumnType("int");

                b.Property<int?>("adr_IdZmienil")
                    .HasColumnType("int");

                b.Property<string>("adr_Kod")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Miejscowosc")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_NIP")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Nazwa")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_NazwaPelna")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_NrDomu")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_NrEORI")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_NrLokalu")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_NrUrzeduSkarbowego")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Poczta")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Powiat")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Skrytka")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Symbol")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("adr_Telefon")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("adr_TypAdresu")
                    .HasColumnType("int");

                b.Property<string>("adr_Ulica")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("adr_Id");

                b.ToTable("adr__Ewid");
            });

            modelBuilder.Entity("MasterDetail.AdrEmail", b =>
                {
                    b.Property<int>("am_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdrEwidadr_Id")
                        .HasColumnType("int");

                    b.Property<int>("FK_adr_Email_adr__Ewid")
                        .HasColumnType("int");

                    b.Property<string>("am_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("am_IdAdres")
                        .HasColumnType("int");

                    b.Property<bool>("am_Podstawowy")
                        .HasColumnType("bit");

                    b.Property<int>("am_Rodzaj")
                        .HasColumnType("int");

                    b.HasKey("am_Id");

                    b.HasIndex("AdrEwidadr_Id");

                    b.ToTable("adr_Email");
                });

            modelBuilder.Entity("MasterDetail.AdrEmail", b =>
                {
                    b.HasOne("MasterDetail.AdrEwid", "AdrEwid")
                        .WithMany("AdrEwid")
                        .HasForeignKey("AdrEwidadr_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
